spring:
  application:
    name: assistance

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: ERROR

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:1800000}

auth:
  user: ${USER_AUTH}
  password: ${PASSWORD_AUTH}

server:
  port: 8000
